function [ fig_EPG,ax_EPG,...
            fig_ENTRAINMENT,ax_ENTRAINMENT,cb_ENTRAINMENT,...
            fig_PARTICLE_CONCENTRATION,ax_PARTICLE_CONCENTRATION,cb_PARTICLE_CONCENTRATION,...
            fig_GAS_TEMPERATURE,ax_GAS_TEMPERATURE,cb_GAS_TEMPERATURE,...
            fig_BULK_DENSITY,ax_BULK_DENSITY,cb_BULK_DENSITY,...
            fig_RELATIVE_DENSITY,ax_RELATIVE_DENSITY,cb_RELATIVE_DENSITY,...
            fig_VELOCITY,ax_VELOCITY,cb_VELOCITY,...
            fig_VORTICITY,ax_VORTICITY,cb_VORTICITY,...
            fig_MASS_FLUX,ax_MASS_FLUX,cb_MASS_FLUX] ...
            = initializeFigures
%initializeFigures Summary of this function goes here #TODO
%   Detailed explanation goes here #TODO
%
%   Last edit: Taryn Black, 25 July 2016

nmap = 256;


%%  Global variables that are used
    global VIEW3D_AZIMUTH VIEW3D_ELEVATION
    global SLICE_AZIMUTH SLICE_ELEVATION
    global COLORRANGE_ENTRAINMENT COLORRANGE_PARTICLE_CONCENTRATION ...
        COLORRANGE_GAS_TEMPERATURE COLORRANGE_BULK_DENSITY ...
        COLORRANGE_RELATIVE_DENSITY COLORRANGE_VELOCITY ...
        COLORRANGE_VORTICITY COLORRANGE_MASS_FLUX
    global PLUME_EDGE
    
%%  Gas volume fraction
%   3D figure, isosurface, viewed at angle, single panel
    [fig_EPG,ax_EPG,cb_EPG] = createHandles(VIEW3D_AZIMUTH,VIEW3D_ELEVATION,...
        'Gas Volume Fraction',[0 0 12.5 18.75],'default',[0 0]);
    delete(cb_EPG);
    
%%  Entrainment isosurfaces
%   3D figure, isosurface, viewed at angle, single panel
%   Custom colormap and colorbar labels
    COLORMAP_ENTRAINMENT = [winter(round(nmap*-COLORRANGE_ENTRAINMENT(1)/...
        (diff(COLORRANGE_ENTRAINMENT))));[0.9 0.9 0.9];...
        flipud(autumn(nmap-round(nmap*-COLORRANGE_ENTRAINMENT(1)/...
        (diff(COLORRANGE_ENTRAINMENT)))))];
    [fig_ENTRAINMENT,ax_ENTRAINMENT,cb_ENTRAINMENT] = ...
        createHandles(VIEW3D_AZIMUTH,VIEW3D_ELEVATION,'Entrainment',...
        [16 0 20 18.75],COLORMAP_ENTRAINMENT,COLORRANGE_ENTRAINMENT);
    
%%  Particle concentration
%   3D figure, filled contours, viewed as slice, multiple panels
    [fig_PARTICLE_CONCENTRATION,ax_PARTICLE_CONCENTRATION,...
        cb_PARTICLE_CONCENTRATION] = ...
        createHandles(SLICE_AZIMUTH,SLICE_ELEVATION,'Particle Concentration',...
        [0 0.83 32 17.5],'jet',COLORRANGE_PARTICLE_CONCENTRATION,3);
    cb_PARTICLE_CONCENTRATION.Label.String = '\bflog_{10}(Particle volume fraction)';
    
%%  Gas temperature
%   3D figure, filled contours, viewed as slice, contains overlay contours,
%   single panel
    COLOR_VALUES_PARTICLE_CONCENTRATION = log10(-PLUME_EDGE+1):1:-2;
    COLORMAP_PARTICLE_CONCENTRATION = ...
        colormap(flipud(bone(length(COLOR_VALUES_PARTICLE_CONCENTRATION))));
    [fig_GAS_TEMPERATURE,ax_GAS_TEMPERATURE,cb_GAS_TEMPERATURE] = ...
        createHandles(SLICE_AZIMUTH,SLICE_ELEVATION,'Gas Temperature',...
        [16.66 0 21.5 18.75],'default',COLORRANGE_GAS_TEMPERATURE);
    cb_GAS_TEMPERATURE.Label.String = '\bfTemperature [K]';
    %   Add particle concentration overlays #TODO

%%  Bulk density
%   3D figure, filled contours, viewed as slice, single panel
    [fig_BULK_DENSITY,ax_BULK_DENSITY,cb_BULK_DENSITY] = ...
        createHandles(SLICE_AZIMUTH,SLICE_ELEVATION,'Bulk Density',...
        [0 0 19 18.75],'default',COLORRANGE_BULK_DENSITY);
    cb_BULK_DENSITY.Label.String = '\bfBulk Density [kg/m^3]';
    
%%  Relative density
%   3D figure, filled contours, viewed as slice, custom colormap, single
%   panel
    cmaplims = [1 0 0;    % red
                1 1 1;    % white
                0 0 1];   % blue
    fixcpts = [nmap-1 nmap*(1-(abs(COLORRANGE_RELATIVE_DENSITY(2))/...
        (abs(COLORRANGE_RELATIVE_DENSITY(1))+...
        abs(COLORRANGE_RELATIVE_DENSITY(2))))) 0];
    COLORMAP_RELATIVE_DENSITY = interp1(fixcpts/nmap,cmaplims,linspace(0,1,nmap));
    [fig_RELATIVE_DENSITY,ax_RELATIVE_DENSITY,cb_RELATIVE_DENSITY] = ...
        createHandles(SLICE_AZIMUTH,SLICE_ELEVATION,'Relative Density',...
        [16.66 0 19 18.75],COLORMAP_RELATIVE_DENSITY,COLORRANGE_RELATIVE_DENSITY);
    cb_RELATIVE_DENSITY.Label.String = '\bf\rho_{atmosphere} - \rho_{mixture} [kg/m^3]';

%%  Velocity
%   3D figure, filled contours, viewed as slice, single panel
    [fig_VELOCITY,ax_VELOCITY,cb_VELOCITY] = ...
        createHandles(SLICE_AZIMUTH,SLICE_ELEVATION,'Velocity',...
        [0 0 18 18.75],'default',COLORRANGE_VELOCITY);
    cb_VELOCITY.Label.String = '\bfVelocity [m/s]';
    
%%  Vorticity
%   3D figure, isosurface, viewed at angle, multiple panels
    [fig_VORTICITY,ax_VORTICITY,cb_VORTICITY] = ...
        createHandles(SLICE_AZIMUTH,SLICE_ELEVATION,'Vorticity',...
        [0 0 30 18],'default',COLORRANGE_VORTICITY,2);
    cb_VORTICITY.Label.String = '\bfFlow Vorticity (s^{-1})';
    
%%  Mass flux
%   3D figure, filled contours, viewed as slice, multiple panels
    COLORMAP_MASS_FLUX = [winter;[0.9 0.9 0.9];flipud(autumn)];
    [fig_MASS_FLUX,ax_MASS_FLUX,cb_MASS_FLUX] = ...
        createHandles(SLICE_AZIMUTH,SLICE_ELEVATION,'Solid Mass Flux',...
        [0 0 33 18.75],COLORMAP_MASS_FLUX,COLORRANGE_MASS_FLUX,2);
    cb_MASS_FLUX.Label.String = '\bfMass Flux (kg/m^2s)';   
    cb_MASS_FLUX.Ticks = COLORRANGE_MASS_FLUX(1):COLORRANGE_MASS_FLUX(2);
    cb_MASS_FLUX.TickLabels = cellstr(num2str(...
        [-logspace(-COLORRANGE_MASS_FLUX(1),1,-COLORRANGE_MASS_FLUX(1)) ...
         0 ...
         logspace(1,COLORRANGE_MASS_FLUX(2),COLORRANGE_MASS_FLUX(2))],...
        '%.0e\n'));
    view(ax_MASS_FLUX(2),VIEW3D_AZIMUTH,VIEW3D_ELEVATION);
    
    
end

