function [ EPG,EPS1,EPS2,EPS3,...
    U_G,V_G,W_G,...
    T_G,RO_G,...
    V_S1,V_S2,V_S3 ] = loadTimestepData( t )
%loadTimestepData Summary of this function goes here #TODO
%   Detailed explanation goes here #TODO
%
%   Last edit: Taryn Black, 11 July 2016

%%  Global variables that are used
    global DATAPATH POSTPATH
    global IMAX JMAX KMAX GHOSTCELLS_IJK
    global FILENAME_EPG FILENAME_EPS1 FILENAME_EPS2 FILENAME_EPS3 ...
        FILENAME_UG FILENAME_VG FILENAME_WG FILENAME_TG FILENAME_ROG ...
        FILENAME_VS1 FILENAME_VS2 FILENAME_VS3
    global READ_EPG READ_EPS1 READ_EPS2 READ_EPS3 READ_UG READ_VG ...
        READ_WG READ_TG READ_ROG READ_VS1 READ_VS2 READ_VS3
    global IMPORTSPEC_EPG IMPORTSPEC_EPS1 IMPORTSPEC_EPS2 IMPORTSPEC_EPS3 ...
        IMPORTSPEC_UG IMPORTSPEC_VG IMPORTSPEC_WG IMPORTSPEC_TG ...
        IMPORTSPEC_ROG IMPORTSPEC_VS1 IMPORTSPEC_VS2 IMPORTSPEC_VS3

    
%%  Create file IDs for current timestep
    cd(DATAPATH)
    fclose('all');
    clear fID*;
    cd(POSTPATH)
    
    fID_EPG  = fileReadType(FILENAME_EPG,READ_EPG,t,DATAPATH,POSTPATH);
    fID_EPS1 = fileReadType(FILENAME_EPS1,READ_EPS1,t,DATAPATH,POSTPATH);
    fID_EPS2 = fileReadType(FILENAME_EPS2,READ_EPS2,t,DATAPATH,POSTPATH);
    fID_EPS3 = fileReadType(FILENAME_EPS3,READ_EPS3,t,DATAPATH,POSTPATH);
    fID_UG   = fileReadType(FILENAME_UG,READ_UG,t,DATAPATH,POSTPATH);
    fID_VG   = fileReadType(FILENAME_VG,READ_VG,t,DATAPATH,POSTPATH);
    fID_WG   = fileReadType(FILENAME_WG,READ_WG,t,DATAPATH,POSTPATH);
    fID_TG   = fileReadType(FILENAME_TG,READ_TG,t,DATAPATH,POSTPATH);
    fID_ROG  = fileReadType(FILENAME_ROG,READ_ROG,t,DATAPATH,POSTPATH);
    fID_VS1  = fileReadType(FILENAME_VS1,READ_VS1,t,DATAPATH,POSTPATH);
    fID_VS2  = fileReadType(FILENAME_VS2,READ_VS2,t,DATAPATH,POSTPATH);
    fID_VS3  = fileReadType(FILENAME_VS3,READ_VS3,t,DATAPATH,POSTPATH);
    
%%  Read and reshape values for current timestep
    EPG = loadTimestep3D(fID_EPG,IMPORTSPEC_EPG,READ_EPG,IMAX,JMAX,KMAX,GHOSTCELLS_IJK);
    EPS1 = loadTimestep3D(fID_EPS1,IMPORTSPEC_EPS1,READ_EPS1,IMAX,JMAX,KMAX,GHOSTCELLS_IJK);
    EPS2 = loadTimestep3D(fID_EPS2,IMPORTSPEC_EPS2,READ_EPS2,IMAX,JMAX,KMAX,GHOSTCELLS_IJK);
    EPS3 = loadTimestep3D(fID_EPS3,IMPORTSPEC_EPS3,READ_EPS3,IMAX,JMAX,KMAX,GHOSTCELLS_IJK);
    U_G = loadTimestep3D(fID_UG,IMPORTSPEC_UG,READ_UG,IMAX,JMAX,KMAX,GHOSTCELLS_IJK);
    V_G = loadTimestep3D(fID_VG,IMPORTSPEC_VG,READ_VG,IMAX,JMAX,KMAX,GHOSTCELLS_IJK);
    W_G = loadTimestep3D(fID_WG,IMPORTSPEC_WG,READ_WG,IMAX,JMAX,KMAX,GHOSTCELLS_IJK);
    T_G = loadTimestep3D(fID_TG,IMPORTSPEC_TG,READ_EPG,IMAX,JMAX,KMAX,GHOSTCELLS_IJK);
    RO_G = loadTimestep3D(fID_ROG,IMPORTSPEC_ROG,READ_ROG,IMAX,JMAX,KMAX,GHOSTCELLS_IJK);
    V_S1 = loadTimestep3D(fID_VS1,IMPORTSPEC_VS1,READ_VS1,IMAX,JMAX,KMAX,GHOSTCELLS_IJK);
    V_S2 = loadTimestep3D(fID_VS2,IMPORTSPEC_VS2,READ_VS2,IMAX,JMAX,KMAX,GHOSTCELLS_IJK);
    V_S3 = loadTimestep3D(fID_VS3,IMPORTSPEC_VS3,READ_VS3,IMAX,JMAX,KMAX,GHOSTCELLS_IJK);


end

